import { defineConfig } from 'vite'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import fs from 'fs'
import path from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Helper to clean static directory
function cleanStaticDir() {
  const staticDir = path.resolve(__dirname, '../resources/static')
  if (fs.existsSync(staticDir)) {
    fs.readdirSync(staticDir).forEach(file => {
      // Only delete files generated by Vite (you can refine this pattern)
      if (/^main-.*\.(js|css)$/.test(file)) {
        fs.unlinkSync(path.join(staticDir, file))
      }
    })
    console.log('Cleaned Vite-generated files in static folder')
  }
}


export default defineConfig({
  build: {
    outDir: '../resources/',
    assetsDir: 'static',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'templates/flight.html'),
      },
    },
  },
  plugins: [
    {
      name: 'clean-static-before-build',
      buildStart() {
        cleanStaticDir()
      }
    },

  ]
})
